# Generated by Django 2.0.1 on 2018-11-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='employee_name',
            new_name='user',
        ),
    ]
