# Generated by Django 2.0.1 on 2018-11-25 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181125_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='da',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='hra',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='ma',
        ),
        migrations.AddField(
            model_name='salary',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='month',
            field=models.CharField(choices=[('P1', 'Professor'), ('P2', 'Associate Professor'), ('P3', 'Assistant Professor'), ('L1', 'Lab Assistant')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pay_grade',
            field=models.CharField(choices=[('P1', 'Professor'), ('P2', 'Associate Professor'), ('P3', 'Assistant Professor'), ('L1', 'Lab Assistant')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
