# Generated by Django 2.0.1 on 2018-10-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181024_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
