# Generated by Django 2.0.1 on 2018-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181125_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.CharField(choices=[('1', 'Januvary'), ('2', 'Februvary'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='', max_length=5),
        ),
    ]
