# Generated by Django 2.0.1 on 2018-10-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181024_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Accountant'), ('3', 'Staff')], default=3, max_length=2),
        ),
    ]
