# Generated by Django 2.0.1 on 2018-11-25 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181125_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
