# Generated by Django 2.0.1 on 2018-11-25 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181125_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='hours',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)]),
        ),
    ]
