# Generated by Django 2.0.1 on 2018-11-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181024_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Accountant'), ('3', 'Staff')], max_length=2),
        ),
    ]
