# Generated by Django 2.0.1 on 2018-11-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181125_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='days',
        ),
        migrations.AlterField(
            model_name='salary',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
