# Generated by Django 2.0.1 on 2018-11-26 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181125_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='relatedusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
