# Generated by Django 2.0.1 on 2018-11-26 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181126_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='identify',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='relatedjobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
